# schema version '3' does not support 'extends' keyword anymore
# https://stackoverflow.com/questions/52587643/how-to-extend-service-in-docker-compose-v3

version: "3.9"
services:
  trezor-user-env-unix:
    image: ghcr.io/trezor/trezor-user-env:36dfd1174f56dde0b0b85b3acd927bfda4a63043
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - LOCAL_USER_ID=$LOCAL_USER_ID
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw

  suite-dev:
    container_name: suite-dev
    extends:
      service: suite-base
      file: docker-compose.suite-base.yml
    command: bash -c "yarn suite:dev"
