version: "3.9"
services:
  trezor-user-env-unix:
    image: ghcr.io/trezor/trezor-user-env:36dfd1174f56dde0b0b85b3acd927bfda4a63043
    environment:
      - SDL_VIDEODRIVER=dummy
      - XDG_RUNTIME_DIR=/var/tmp
    network_mode: host
    # in case local developement on mac is needed, these ports will be useful
    # ports:
    #   - "9002:9002"
    #   - "9001:9001"
    #   - "21326:21326"
    #   - "21325:21326"
